export const terminalThemeTokens = {
  surface: {
    canvas: "#05070b",
    canvasAlt: "#06080c",
    panel: "#0c0f14",
    panelAlt: "#121722",
    overlay: "#0b0f15",
  },
  border: {
    subtle: "#232937",
    default: "#2a2f3a",
    strong: "#3a4250",
  },
  text: {
    primary: "#d8dde7",
    secondary: "#aeb8c8",
    muted: "#8e98a8",
    inverse: "#05070b",
  },
  accent: {
    primary: "#ff9f1a",
    primaryAlt: "#f57c20",
    warning: "#ffb74d",
    info: "#4ea1ff",
    cyan: "#4dd0e1",
  },
  market: {
    up: "#00c176",
    down: "#ff4d4f",
    neutral: "#8e98a8",
    candleUp: "#26a69a",
    candleDown: "#ef5350",
  },
  risk: {
    low: "#00c176",
    medium: "#ffb74d",
    high: "#ff4d4f",
    critical: "#ff4d4f",
  },
  system: {
    ok: "#00c176",
    stale: "#ffb74d",
    warning: "#ffb74d",
    critical: "#ff4d4f",
    offline: "#8e98a8",
  },
  chart: {
    drawingTrend: "#ffd166",
    drawingHLine: "#4dd0e1",
    indicatorOverlay: "#4ea1ff",
    indicatorPane: "#ffb74d",
    accentAreaTop: "#ff9f1a55",
    accentAreaBottom: "#ff9f1a12",
    infoAreaTop: "#5aa9ff55",
    infoAreaBottom: "#5aa9ff12",
    candleUpFillStrong: "#26a69a44",
    candleUpFillSoft: "#26a69a11",
    candleDownFillStrong: "#ef535044",
    candleDownFillSoft: "#ef535011",
    candleUpAlpha80: "#26a69a80",
    candleDownAlpha80: "#ef535080",
    candleUpAlpha88: "#26a69a88",
    candleDownAlpha88: "#ef535088",
  },
} as const;

export const terminalSemanticColorRoles = {
  shell: {
    background: terminalThemeTokens.surface.canvasAlt,
    panel: terminalThemeTokens.surface.panel,
    border: terminalThemeTokens.border.default,
  },
  status: {
    ok: terminalThemeTokens.system.ok,
    stale: terminalThemeTokens.system.stale,
    warning: terminalThemeTokens.system.warning,
    critical: terminalThemeTokens.system.critical,
    offline: terminalThemeTokens.system.offline,
  },
  market: {
    up: terminalThemeTokens.market.up,
    down: terminalThemeTokens.market.down,
    neutral: terminalThemeTokens.market.neutral,
  },
  risk: {
    low: terminalThemeTokens.risk.low,
    medium: terminalThemeTokens.risk.medium,
    high: terminalThemeTokens.risk.high,
    critical: terminalThemeTokens.risk.critical,
  },
} as const;

// Compatibility export for existing chart/table components.
export const terminalColors = {
  bg: terminalThemeTokens.surface.canvas,
  panel: terminalThemeTokens.surface.panel,
  border: terminalThemeTokens.border.default,
  borderStrong: terminalThemeTokens.border.strong,
  text: terminalThemeTokens.text.primary,
  muted: terminalThemeTokens.text.muted,
  accent: terminalThemeTokens.accent.primary,
  accentAlt: terminalThemeTokens.accent.primaryAlt,
  positive: terminalThemeTokens.market.up,
  negative: terminalThemeTokens.market.down,
  warning: terminalThemeTokens.accent.warning,
  info: terminalThemeTokens.accent.info,
  candleUp: terminalThemeTokens.market.candleUp,
  candleDown: terminalThemeTokens.market.candleDown,
  drawingTrend: terminalThemeTokens.chart.drawingTrend,
  drawingHLine: terminalThemeTokens.chart.drawingHLine,
  indicatorOverlay: terminalThemeTokens.chart.indicatorOverlay,
  indicatorPane: terminalThemeTokens.chart.indicatorPane,
  accentAreaTop: terminalThemeTokens.chart.accentAreaTop,
  accentAreaBottom: terminalThemeTokens.chart.accentAreaBottom,
  candleUpFillStrong: terminalThemeTokens.chart.candleUpFillStrong,
  candleUpFillSoft: terminalThemeTokens.chart.candleUpFillSoft,
  candleDownFillStrong: terminalThemeTokens.chart.candleDownFillStrong,
  candleDownFillSoft: terminalThemeTokens.chart.candleDownFillSoft,
  candleUpAlpha80: terminalThemeTokens.chart.candleUpAlpha80,
  candleDownAlpha80: terminalThemeTokens.chart.candleDownAlpha80,
  candleUpAlpha88: terminalThemeTokens.chart.candleUpAlpha88,
  candleDownAlpha88: terminalThemeTokens.chart.candleDownAlpha88,
  infoAreaTop: terminalThemeTokens.chart.infoAreaTop,
  infoAreaBottom: terminalThemeTokens.chart.infoAreaBottom,
} as const;

export const terminalOverlayPalette = [
  terminalThemeTokens.accent.primary,
  terminalThemeTokens.accent.cyan,
  "#66bb6a",
  terminalThemeTokens.chart.drawingTrend,
  terminalThemeTokens.text.muted,
  terminalThemeTokens.accent.warning,
] as const;
